### ISSUE TITLE
Have call-to-arms banner for initial period

### ISSUE THREAD

**Issue by stestagg** [pythonjobs/jobs#11]
In order to drive traffic, and build a community, a short call-to-arms statement on the homepage will help.

This is something we can add, then phase out as things progress

**Comment by salimfadhley** [comment]
If you decide to do this I can write some copy - do you want it to just explain the guiding principles of the site? That sort of thing?

**Comment by stestagg** [comment]
Dan's idea was to actually have a box that asks people tp link to the site, and share it, to build it's profile, and gain momentum

**Comment by salimfadhley** [comment]
yes, let's do this. I've absolutely no idea how but will have a go if you give me a clue. (might be better if you do this one if you can spare the time!)

**Comment by stestagg** [comment]
Closing this :D, can still do it if anyone wants
