### ISSUE TITLE
Instructions for self-hosting dont seem to work

### ISSUE THREAD

**Issue by salimfadhley** [pythonjobs/jobs#15]
When I fire up a self-hosted site with "hyde serve" all I get is an empty site.

That is to say that I see the banner and logo but not any content, despite having copied the content into the hyde/content/jobs directory.

**Comment by stestagg** [comment]
I wonder about having some 'test-my-change' scripts in the jobs repo that run everything for you, so people don't have to checkout the template repo and copy things over manually, not 100% sure how it would work tho, and harder to do in a cross-platform way. 

Something like:

1. set up a virtualenv with the dependencies
2. check out the templates repo
3. symlink (or something) the jobs dir into the right place
4. remove the deploy/ dir
5 run the hyde serve

**Comment by salimfadhley** [comment]
I changed the instructions a bit - now they work.
