### ISSUE TITLE
All tags should be lowercase

### ISSUE THREAD

**Issue by salimfadhley** [pythonjobs/jobs#18]
Since we don't currently reject tags that are upper-case, let's make it so that all tags are grouped in a case-insensitive kind of way.

That way the tag "London" and "LONDON" and "London" will all mean the same thing but will display as "london".

**Comment by stestagg** [comment]
Totally, I had naively assumed that the tagging code would handle this
already.

We might be able to make the plugin convert automatically?

**Comment by salimfadhley** [comment]
@stestagg can you expand on this proposed solution? Should the plugin actually modify the files or just change the way that the tags are compiled?

**Comment by stestagg** [comment]
I /think/ but am not sure, that the metadata dictionary can be modified by
the plugin. We might have to change the order of the plugins in site.yaml
so that ours is before the tagging plugin.

**Comment by salimfadhley** [comment]
That turned out to be a lot easier than I thought - I just added a single line in the plugin (without changing the execution order) which converts all the tags to lower-case.

PR is ready for your scrutiny.

**Comment by salimfadhley** [comment]
I think this is done now.
