### ISSUE TITLE
Global instead of UK-only

### ISSUE THREAD

**Issue by aclark4life** [pythonjobs/jobs#25]
This job board is awesome! How about making it global instead of UK-only?

**Comment by salimfadhley** [comment]
It is international! See the FAQ! :-)

Please feel free to submit whatever you want.

**Comment by aclark4life** [comment]
Ah! In that case would you mind changing the project description? Thanks
![screenshot 2015-03-15 20 30 54](https://cloud.githubusercontent.com/assets/72164/6659047/3da8931e-cb52-11e4-8d28-8d31df0d16ab.png)

**Comment by salimfadhley** [comment]
Will do, excellent suggestion. If you make a pull-request I would be happy to merge your change. I will be online for the next few hours.

**Comment by salimfadhley** [comment]
The change has been made. I'd appreciate your feedback.

**Comment by aclark4life** [comment]
Looks great! Thanks again
