### ISSUE TITLE
YunoJuno job post CI error

### ISSUE THREAD

**Issue by rossmiller** [pythonjobs/jobs#263]
Hi there,

I wonder if you could help us. There is an error with the CI for https://github.com/pythonjobs/jobs/pull/262

I am not sure how to debug this (I'm helping Estella Reid with this). What's the best way to get to a fix?

**Comment by stestagg** [comment]
Hi

Thanks for your submission, sorry about the issues, our CI output isn't
that readable anymore.

The job was missing the contract type.  I've added it back (as permanent)
and the CI passed.

Thanks

Steve

**Comment by rossmiller** [comment]
Steve, you're a legend! Thanks so much.
