### ISSUE TITLE
3 job postings outside `jobs` folder?

### ISSUE THREAD

**Issue by hartwork** [pythonjobs/jobs#320]
Hi!

I stumbled upon 3 job postings that are located at the root folder of the repository rather than the `jobs` folder. They do not seem to be listed on the live website. It's these files:

* [CTO (Mid- to Senior-Level Dev)](https://github.com/pythonjobs/jobs/blob/master/CTO%20(Mid-%20to%20Senior-Level%20Dev)) introduced in 418fed1cb57b8e87a0d0e9236420db0559646a4e
* [Duxe_Sydney_Django.html](https://github.com/pythonjobs/jobs/blob/master/Duxe_Sydney_Django.html) introduced in 5cc444baa7e4bc6da24e24a490cd422c1b1997a7
* [readcoor_cambridge_senior_python_2017-1022.html](https://github.com/pythonjobs/jobs/blob/master/readcoor_cambridge_senior_python_2017-1022.html) introduced in 15dcf7921e41bd23484fb74652ab2d38fa658dce

One of these is as recent as three months old. Should they be deleted, moved to the `jobs` folder or ..?

Best, Sebastian

**Comment by stestagg** [comment]
Thanks for your help with these PRs/issues!

I’ll take a look at the PR tomorrow

We can probably delete these jobs as they never made it onto the site in
the first place. You’ve exposed an issue that I’ve been meaning to get
around to for a while, we never remove old job postings, so some are quite
old now.

Thanks

Steve

**Comment by lordmauve** [comment]
Perhaps they are still valid. We could just move them to `jobs` and deal with expiry separately?

**Comment by hartwork** [comment]
> we never remove old job postings, so some are quite

Sounds related to #275.

**Comment by hartwork** [comment]
Fixed by #322, closing.
