### ISSUE TITLE
Cookie notice

### ISSUE THREAD

**Issue by stestagg** [pythonjobs/jobs#44]
We should probably add some text on the select tags filter to let users know that this is being stored in a 'cookie'.  It may be localstorage, but the same rules apply, and the ICO guidance isn't 100% clear on if we need it or not. (https://ico.org.uk/media/for-organisations/documents/1545/cookies_guidance.pdf)

We can make the text discreet, and unobtrusive, so it seems to make sense to just add it

**Comment by lordmauve** [comment]
I propose not to fix this. Cookie law is stupid and unenforceable, and we're not even using cookies or tracking.
