### ISSUE TITLE
Can we use Google Maps API to visually show the location of all the jobs in our database?

### ISSUE THREAD

**Issue by salimfadhley** [pythonjobs/jobs#57]
It would be cool if we could use the collected user data to show a map with every Python job we have with a pin.

That would take our PAAS approach to another extreme.

**Comment by stestagg** [comment]
This is an epic idea.  It's basically not too hard, except we don't have reliable location information for the jobs.  

The build script could look up actual coordinates from the locations, but that /does/ mean that we might get the location wrong, then the first time the submitter knows about it is when it goes live.

**Comment by stestagg** [comment]
What do you think?

![screenshot 2015-03-29 19 59 40](https://cloud.githubusercontent.com/assets/704526/6887148/596ca570-d64e-11e4-8dcb-27306fbe250e.png)
![screenshot 2015-03-29 19 59 49](https://cloud.githubusercontent.com/assets/704526/6887149/596d05f6-d64e-11e4-8f4a-0d0eb97c6f6b.png)

**Comment by salimfadhley** [comment]
It looks brilliant!!! Merge it.

**Comment by salimfadhley** [comment]
I quite like having the map in the background - it looks so cool.

**Comment by lordmauve** [comment]
I'd always assumed we were going to go this route, but the UX on Google
Maps sucks when you have a small number of global locations in a small
number of clusters. It's also bad/slow on mobile.

IIRC Djangopeople.org did much better than this by combining a Google map
with a list of items within each displayed map area.

**Comment by lordmauve** [comment]
Also the wrapping of the "Jobs by location" is a bit ugly on mobile when
you select two or three tags.

Could it just be called "Map" instead of "Jobs by location" until we can
make it serve that purpose better? Makes it clearer what to expect.

**Comment by salimfadhley** [comment]
+1 for map!
